// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20220721114534_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoDeAlquilerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoDeAlquilerId");

                    b.HasIndex("ISBN");

                    b.ToTable("Alquileres", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EstadoDeAlquiler", b =>
                {
                    b.Property<int>("EstadoDeAlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoDeAlquilerId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("EstadoDeAlquilerId");

                    b.ToTable("EstadoDeAlquileres", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoDeAlquilerId = 1,
                            Descripcion = "Reservado"
                        },
                        new
                        {
                            EstadoDeAlquilerId = 2,
                            Descripcion = "Alquilado"
                        },
                        new
                        {
                            EstadoDeAlquilerId = 3,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Stock")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ISBN");

                    b.ToTable("Libros", (string)null);

                    b.HasData(
                        new
                        {
                            ISBN = "9788478290598",
                            Autor = "Erich Gamma",
                            Edicion = "2002",
                            Editorial = "ADDISON WESLEY",
                            Imagen = "https://bit.ly/3njK38N",
                            Stock = 10,
                            Titulo = "Patrones de Diseño"
                        },
                        new
                        {
                            ISBN = "9788441526372",
                            Autor = "Beaulieu Alan",
                            Edicion = "2009",
                            Editorial = "ANAYA MULTIMEDIA",
                            Imagen = "https://bit.ly/3tWVIhy",
                            Stock = 10,
                            Titulo = "Aprende SQL"
                        },
                        new
                        {
                            ISBN = "9788437604947",
                            Autor = "Gabriel Garcia Marquez",
                            Edicion = "2007",
                            Editorial = "Ediciones Cátedra",
                            Imagen = "https://bit.ly/3HMVDmm",
                            Stock = 10,
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            ISBN = "9789504935575",
                            Autor = "Gabriel Rolon",
                            Edicion = "2013",
                            Editorial = "Planeta Publishing",
                            Imagen = "https://bit.ly/3nc2jB1",
                            Stock = 10,
                            Titulo = "Palabras Cruzadas"
                        },
                        new
                        {
                            ISBN = "9789506444808",
                            Autor = "King Stephen",
                            Edicion = "2018",
                            Editorial = "Plaza & Janes Editores",
                            Imagen = "https://bit.ly/3zW9ViN",
                            Stock = 10,
                            Titulo = "El Visitante"
                        },
                        new
                        {
                            ISBN = "9782409014932",
                            Autor = "Godoc Eric",
                            Edicion = "2018",
                            Editorial = "Eni",
                            Imagen = "https://bit.ly/3Nq8w7m",
                            Stock = 10,
                            Titulo = "SQL 'Los fundamentos del lenguaje' "
                        },
                        new
                        {
                            ISBN = "9789506445386",
                            Autor = "King Stephen",
                            Edicion = "2020",
                            Editorial = "Plaza & Janes Editores",
                            Imagen = "https://bit.ly/3xNnyyc",
                            Stock = 10,
                            Titulo = "La Sangre Manda"
                        },
                        new
                        {
                            ISBN = "9789504970934",
                            Autor = "Gabriel Rolon",
                            Edicion = "2021",
                            Editorial = "Planeta Publishing",
                            Imagen = "https://bit.ly/3A2pxBu",
                            Stock = 10,
                            Titulo = "El duelo"
                        },
                        new
                        {
                            ISBN = "9786125020024",
                            Autor = "Montero Rosa",
                            Edicion = "2021",
                            Editorial = "Alfaguara",
                            Imagen = "https://bit.ly/3Ojwt1j",
                            Stock = 10,
                            Titulo = "La Buena Suerte"
                        },
                        new
                        {
                            ISBN = "9788417289362",
                            Autor = "Capel Tuñon Manuel I",
                            Edicion = "2022",
                            Editorial = "GARCETA GRUPO EDITORIAL",
                            Imagen = "https://bit.ly/3ygRfsU",
                            Stock = 10,
                            Titulo = "Programación concurrente y en tiempo real"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Alquiler", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("AlquilerNavigator")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EstadoDeAlquiler", "EstadoDeAlquiler")
                        .WithMany("AlquilerNavigator")
                        .HasForeignKey("EstadoDeAlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Libro", "Libros")
                        .WithMany("AlquilerNavigator")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoDeAlquiler");

                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("AlquilerNavigator");
                });

            modelBuilder.Entity("Domain.Entities.EstadoDeAlquiler", b =>
                {
                    b.Navigation("AlquilerNavigator");
                });

            modelBuilder.Entity("Domain.Entities.Libro", b =>
                {
                    b.Navigation("AlquilerNavigator");
                });
#pragma warning restore 612, 618
        }
    }
}
